# Generated by Django 4.2.7 on 2025-08-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('token_id', models.CharField(max_length=255)),
                ('contract_address', models.CharField(max_length=255)),
                ('collection_name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('last_sale', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
