# Generated by Django 4.2.7 on 2025-08-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensea', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nft',
            old_name='last_sale',
            new_name='last_sale_date',
        ),
        migrations.RemoveField(
            model_name='nft',
            name='price',
        ),
        migrations.AddField(
            model_name='nft',
            name='collection_slug',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nft',
            name='external_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='last_sale_currency',
            field=models.CharField(default='ETH', max_length=10),
        ),
        migrations.AddField(
            model_name='nft',
            name='last_sale_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='collection_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='nft',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='name',
            field=models.CharField(blank=True, default='Unnamed NFT', max_length=255),
        ),
        migrations.AlterField(
            model_name='nft',
            name='owner',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
