# Generated by Django 4.2.7 on 2025-08-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensea', '0002_rename_last_sale_nft_last_sale_date_remove_nft_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
