# Generated by Django 4.2.7 on 2025-08-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensea', '0003_alter_nft_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='NftCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=10)),
                ('img', models.URLField(blank=True)),
                ('name', models.CharField(max_length=255)),
                ('volume', models.CharField(max_length=100)),
                ('market_cap', models.CharField(max_length=100)),
                ('floor_price', models.CharField(max_length=100)),
                ('avg_price', models.CharField(max_length=100)),
                ('sales', models.CharField(max_length=100)),
                ('asserts', models.CharField(max_length=100)),
                ('owners', models.CharField(max_length=100)),
                ('owners_percent', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='NFT',
        ),
    ]
