# Generated by Django 4.2.7 on 2025-08-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensea', '0004_nftcollection_delete_nft'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftcollection',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
