# Generated by Django 4.2.7 on 2025-08-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opensea', '0005_nftcollection_sentiment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nftcollection',
            name='sentiment',
        ),
        migrations.RemoveField(
            model_name='nftcollection',
            name='sentiment_score',
        ),
    ]
